banking_dbt:
  outputs:
    dev:
      account: ou40348.ap-southeast-1
      database: banking_project
      password: Sambasamba1234
      role: ACCOUNTADMIN
      schema: analytics
      threads: 4
      type: snowflake
      user: SAMBA
      warehouse: COMPUTE_WH
  target: dev
